name: Auto Create Pull Request to Develop

on:
  push:
    branches:
      - 'feature/**'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Auto-create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: develop         
          branch: ${{ github.ref_name }}
          title: 'Auto PR from ${{ github.ref_name }} to develop'
          body: 'Auto create PR from feature to develop'
          commit-message: 'auto merge commit'
          draft: false
          delete-branch: false